LogLevel: "debug" # debug, info, warn, error, fatal
DatabaseURI: "mongodb://localhost:27017" 
DatabaseName: "messaging_service"
UsersCollection: "users"
CacheURI: "redis://localhost:6379" 
Host: "localhost"
Port: 8080
JwtSecretKey: "00c4d49c0fc32cf170ac1ebb0ac6011410af3ac5a0273fbf69d9390bc2b76b73"
JwtPublicKey: "e4fd251f3c2b6c589a9f5525f5e9dd6f7ee6cea2a5d08cd218ea9ea2a3dac17c"


 